-- CREATING A USER AND GIVING IT ALL THE PRIVELAGES

CREATE USER IF NOT EXISTS 'user_0d_1'@'localhost';
SET PASSWORD FOR 'user_0d_1'@'localhost'='user_0d_1_pwd';
GRANT ALL PRIVILAGES ON *.* TO 'user_0d_1'@'localhost';
FLUSH PRIVELAGES;