-- CREATE A TABLE THAT HAS A NOT NULL, AUTO INCREMENTS ITSELF AND IS A PRIMARY KEY

CREATE SCHEMA IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states
(
id INT AUTO INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(256) NOT NULL
);