-- CREATE A TABLE THAT HAS A NOT NULL, AUTO INCREMENTS ITSELF AND IS A PRIMARY KEY ALSO HAS A FOREIGN KEY

CREATE SCHEMA IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;

CREATE TABLE IF NOT EXISTS cities
(
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
state_id INT, FOREIGN KEY (state_id) REFERENCES states(id)
name VARCHAR(256) NOT NULL,

);